<a href="https://colab.research.google.com/github/dhanushnayak/BERT/blob/main/MRPC_AND__WINOGARD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

from transformers import AutoTokenizer,TFAutoModelForSequenceClassification
import tensorflow as tf


MRPC: takes pair of sentence and determine the closeness  by 
* paraphrase (thoughts and idea)  compare the thoughts by senetence paraphase corpus is used 
* semantic equivalent 

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased-finetuned-mrpc")
model = TFAutoModelForSequenceClassification.from_pretrained("bert-base-cased-finetuned-mrpc")

Some layers from the model checkpoint at bert-base-cased-finetuned-mrpc were not used when initializing TFBertForSequenceClassification: ['dropout_183']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at bert-base-cased-finetuned-mrpc.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [ ]:
classes  = ['Not','Same']

seq_a  = "A+B^^2 is a formula"
seq_b = "abc def the fucntion to render positive and negative formula"


In [ ]:
paraphrase = tokenizer.encode_plus(seq_a,seq_b,return_tensors='tf')

In [ ]:
paraphrase['input_ids'] # takes 2 sequence formes one vector and return yes or no

<tf.Tensor: shape=(1, 27), dtype=int32, numpy=
array([[  101,   138,   116,   139,   167,   167,   123,  1110,   170,
         7893,   102,   170,  1830,  1665, 19353,  1103,   175, 21977,
        14964,  1320,  1106, 19566,  3112,  1105,  4366,  7893,   102]],
      dtype=int32)>

In [ ]:
model(paraphrase)

TFSequenceClassifierOutput([('logits',
                             <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 1.1772947 , -0.94424295]], dtype=float32)>)])

In [ ]:
logits  = model(paraphrase)[0]

In [ ]:
tf.nn.softmax(logits,axis=1)#.numpy()

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.89297897, 0.10702103]], dtype=float32)>

In [ ]:
result = tf.nn.softmax(logits,axis=1).numpy()[0]

**Note** : Index in classes if 0 - No, 1 - Yes, ie. the classes will be ["No","Yes"]

In [ ]:
import numpy as np
for i,j in zip(classes,result):
  print(f"Score for {i} = {j}")

Score for Not = 0.8929789662361145
Score for Same = 0.1070210263133049


**Winograd schemas**

converting to other language, and maintaining pronoun



In [2]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.7 MB 12.7 MB/s 
     |████████████████████████████████| 101 kB 8.4 MB/s 
     |████████████████████████████████| 596 kB 31.9 MB/s 
     |████████████████████████████████| 6.6 MB 40.8 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [3]:
from transformers import pipeline
translator = pipeline("translation_en_to_fr")

No model was supplied, defaulted to t5-base and revision 686f1db (https://huggingface.co/t5-base).
Using a pipeline without specifying a model name and revision in production is not recommended.


/usr/local/lib/python3.7/dist-packages/transformers/models/t5/tokenization_t5_fast.py:166: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.
For now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.
- Be aware that you SHOULD NOT rely on t5-base automatically truncating your input to 512 when padding/encoding.
- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.
- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.
  FutureWarning,


In [4]:
translator("How to say hi in french",max_length=40)

[{'translation_text': 'Comment dire hi en français'}]