<a href="https://colab.research.google.com/github/dhanushnayak/BERT/blob/main/MRPC_AND__WINOGARD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

from transformers import AutoTokenizer,TFAutoModelForSequenceClassification
import tensorflow as tf


MRPC: takes pair of sentence and determine the closeness  by 
* paraphrase (thoughts and idea)  compare the thoughts by senetence paraphase corpus is used 
* semantic equivalent 

In [3]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased-finetuned-mrpc")
model = TFAutoModelForSequenceClassification.from_pretrained("bert-base-cased-finetuned-mrpc")

Some layers from the model checkpoint at bert-base-cased-finetuned-mrpc were not used when initializing TFBertForSequenceClassification: ['dropout_183']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at bert-base-cased-finetuned-mrpc.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [16]:
classes  = ['Not','Same']

seq_a  = "A+B^^2 is a formula"
seq_b = "abc def the fucntion to render positive and negative formula"


In [14]:
paraphrase = tokenizer.encode_plus(seq_a,seq_b,return_tensors='tf')

In [15]:
paraphrase['input_ids'] # takes 2 sequence formes one vector and return yes or no

<tf.Tensor: shape=(1, 27), dtype=int32, numpy=
array([[  101,   138,   116,   139,   167,   167,   123,  1110,   170,
         7893,   102,   170,  1830,  1665, 19353,  1103,   175, 21977,
        14964,  1320,  1106, 19566,  3112,  1105,  4366,  7893,   102]],
      dtype=int32)>

In [7]:
model(paraphrase)

TFSequenceClassifierOutput([('logits',
                             <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 1.1772947 , -0.94424295]], dtype=float32)>)])

In [8]:
logits  = model(paraphrase)[0]

In [9]:
tf.nn.softmax(logits,axis=1)#.numpy()

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.89297897, 0.10702103]], dtype=float32)>

In [11]:
result = tf.nn.softmax(logits,axis=1).numpy()[0]

**Note** : Index in classes if 0 - No, 1 - Yes, ie. the classes will be ["No","Yes"]

In [17]:
import numpy as np
for i,j in zip(classes,result):
  print(f"Score for {i} = {j}")

Score for Not = 0.8929789662361145
Score for Same = 0.1070210263133049
